# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quoteMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(958, 626)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("font-size: 16px;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 50, 921, 31))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelAuthor = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelAuthor.setObjectName("labelAuthor")
        self.gridLayout.addWidget(self.labelAuthor, 0, 1, 1, 1)
        self.labelQuote = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelQuote.setObjectName("labelQuote")
        self.gridLayout.addWidget(self.labelQuote, 0, 0, 1, 1)
        self.labelRating = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelRating.setObjectName("labelRating")
        self.gridLayout.addWidget(self.labelRating, 0, 2, 1, 1)
        self.labeZerolEditing = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labeZerolEditing.setText("")
        self.labeZerolEditing.setObjectName("labeZerolEditing")
        self.gridLayout.addWidget(self.labeZerolEditing, 0, 3, 1, 1)
        self.labelCategory = QtWidgets.QLabel(self.centralwidget)
        self.labelCategory.setGeometry(QtCore.QRect(10, 10, 371, 31))
        self.labelCategory.setText("")
        self.labelCategory.setObjectName("labelCategory")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 958, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.actionNewQuote = QtWidgets.QAction(MainWindow)
        self.actionNewQuote.setObjectName("actionNewQuote")
        self.actionNewCategory = QtWidgets.QAction(MainWindow)
        self.actionNewCategory.setObjectName("actionNewCategory")
        self.actionGeneralCategory = QtWidgets.QAction(MainWindow)
        self.actionGeneralCategory.setObjectName("actionGeneralCategory")
        self.actionFavCategory = QtWidgets.QAction(MainWindow)
        self.actionFavCategory.setObjectName("actionFavCategory")
        self.menu.addAction(self.actionNewQuote)
        self.menu_3.addAction(self.actionNewCategory)
        self.menu_3.addAction(self.actionFavCategory)
        self.menu_3.addAction(self.actionGeneralCategory)
        self.menu_3.addSeparator()
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelAuthor.setText(_translate("MainWindow", "Автор"))
        self.labelQuote.setText(_translate("MainWindow", "Цитата"))
        self.labelRating.setText(_translate("MainWindow", "Рейтинг"))
        self.menu.setTitle(_translate("MainWindow", "Цитаты"))
        self.menu_3.setTitle(_translate("MainWindow", "Разделы"))
        self.actionNewQuote.setText(_translate("MainWindow", "Новая цитата"))
        self.actionNewCategory.setText(_translate("MainWindow", "Новый раздел"))
        self.actionGeneralCategory.setText(_translate("MainWindow", "Общее"))
        self.actionFavCategory.setText(_translate("MainWindow", "Избранное"))
